# Removed the 'version' attribute as it is obsolete.
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"  # Map container port 8080 to host port 5000
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: